server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass jam_backend:9000;
        fastcgi_index index.php;

        # 🔥 FORZAMOS EL FRONT CONTROLLER
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
    }

    location ~ /\. {
        deny all;
    }
}
